### ISSUE TITLE
2016 MGRA File Hard-Coded in script

### ISSUE THREAD

**Issue by JoeJimFlood** [SANDAG/RSM#25]
The 2016 MGRA file is hard-coded in a [couple](https://github.com/SANDAG/RSM/blob/testing2/scripts/rsm_zone_aggregator.py#L43) [places](https://github.com/SANDAG/RSM/blob/testing2/scripts/rsm_zone_aggregator.py#L55) in the zone aggregator script. This makes running future year scenarios impossible in the RSM. I've tried a couple of workarounds but it will probably just be easier to update the script. There is a property in the property file called [mgra.socec.file](https://github.com/SANDAG/ABM/blob/ABM2_TRUNK/src/main/resources/sandag_abm.properties#L139) that could be referenced.

**Comment by AshishKuls** [comment]
commit acc9e49 solved the issue

**Comment by AshishKuls** [comment]
Done. Year-specific MGRA file name is used by reading the property "mgra.socec.file" from the properties file.
