### ISSUE TITLE
Emmebank matrix aggregator crashes if other run accessing donor model emmebank

### ISSUE THREAD

**Issue by JoeJimFlood** [SANDAG/RSM#26]
One attempt at the 2000-zone baseline run crashed early because it couldn't open the donor model's Emmebank due to an emmelocki file existing. I looked and didn't see it, so I just restarted the run, which completed successfully. I hypothesized that the error was due to two runs I had started at the same time trying to access the donor model's Emmebank at the same time. Looking at the logbooks confirmed this. According to the run's logbook, it attempted to access the donor model's Emmebank at 11:44 AM on March 4:
![image](https://user-images.githubusercontent.com/8129720/223490108-0f09e310-ffc9-4555-a067-6ab0be6539d1.png)

However, another run I had going at the same time was accessing the same Emmebank between 11:40 and 11:47 AM on the same day:
![image](https://user-images.githubusercontent.com/8129720/223491765-3932397a-e549-4905-a28f-840ebe4d7810.png)

This could be a problem if we need to run several runs at the same time and starting them 15 minutes apart might not be feasible. I suppose having a loop that tries accessing it, and then puts a `time.sleep()` call within an except statement might be a possible workaround.

**Comment by AshishKuls** [comment]
added the connection attempt in a [loop](https://github.com/SANDAG/RSM/blob/develop/abm/src/main/emme/toolbox/utilities/databank_aggregator.py#L76).
