### ISSUE TITLE
households_org.csv not in donor model

### ISSUE THREAD

**Issue by JoeJimFlood** [SANDAG/RSM#31]
The data pipeline for the visualizer is looking for a file called households_org.csv, which is not present in the input folder of the donor model. I was able to get it to run by copying and renaming households.csv. The pipeline needs to be edited to not include it, or the instructions need to be edited to show how to properly handle it.

**Comment by arashasadabadi** [comment]
@JoeJimFlood  we have restructured things and now files are not correctly located for households and sampled households. I'm working on this and will report back soon

**Comment by arashasadabadi** [comment]
@JoeJimFlood I changed the structure of the script so there is no longer need for households_org.csv in the input folder of donor model. Instead user needs to bring households.csv file from input folders for each RSM scenario. README file has been updated accordingly.
 You should be able to run it without any problem now. Once you test it successfully please close this issue.

**Comment by JoeJimFlood** [comment]
@arashasadabadi I ran into a memory error while running it on my computer but it worked when I ran it on a modeling server. I'll just watch out to see if the memory error happens again. Thanks!
